apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# config maps
- manifests/config-maps/live-agent-env.yaml

# services
- manifests/services/live-agent-api.yaml
- manifests/services/live-agent-ui.yaml

# deployments
- manifests/deployments/live-agent-api.yaml
- manifests/deployments/live-agent-ui.yaml

# reverse proxy, ingress
- manifests/reverse-proxy/ingress/live-agent-api.yaml
- manifests/reverse-proxy/ingress/live-agent-ui.yaml

patchesJson6902:
# config-map
- target:
    version: v1
    kind: ConfigMap
    name: live-agent-env
  path: overlays/config-maps/live-agent-env_patch.yaml

# reverse-proxy, ingress
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: live-agent-api
  path: overlays/reverse-proxy/ingress/live-agent-api_patch.yaml

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: live-agent-ui
  path: overlays/reverse-proxy/ingress/live-agent-ui_patch.yaml