apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-analytics-odata
spec:
  selector:
    matchLabels:
      app: service-analytics-odata
  replicas: 1
  template:
    metadata:
      labels:
        app: service-analytics-odata
    spec:
      containers:
        - name: service-analytics-odata
          image: 'docker.cognigy.com:5000/service-analytics-odata:f53286bc922ca1d58d0ea1af66b9bf0620f643fd'
          resources:
            requests:
              cpu: '0.1'
              memory: 360M
            limits:
              cpu: '0.5'
              memory: 450M
          envFrom:
            - configMapRef:
                name: cognigy-env
          env:
            - name: ANALYTICS_COLLECTOR_DB_NAME
              value: service-analytics-collector-provider
            - name: SECURITY_DB_NAME
              value: service-security
            - name: CONVERSATION_COLLECTOR_DB_NAME
              value: service-analytics-conversation-collector-provider
            - name: ODATA_SUPER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cognigy-odata
                  key: odata-super-api-key
          volumeMounts:
            - name: rabbitmq-connection-string
              mountPath: /var/run/secrets/rabbitmqConnectionString
              subPath: rabbitmqConnectionString
            - name: analytics-collector-connection-string
              mountPath: /run/secrets/analyticsCollectorConnectionString
              subPath: analyticsCollectorConnectionString
            - name: security-connection-string
              mountPath: /run/secrets/securityConnectionString
              subPath: securityConnectionString
            - name: conversations-connection-string
              mountPath: /run/secrets/conversationsConnectionString
              subPath: conversationsConnectionString
            - name: redis-password
              mountPath: /var/run/secrets/redis-password.conf
              subPath: redis-password.conf
          livenessProbe:
            exec:
              command:
                - node
                - /opt/healthcheck.js
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 10
      volumes:
        - name: rabbitmq-connection-string
          secret:
            secretName: cognigy-rabbitmq
            items:
              - key: connection-string
                path: rabbitmqConnectionString
        - name: analytics-collector-connection-string
          secret:
            secretName: cognigy-service-analytics-collector-provider
            items:
              - key: connection-string
                path: analyticsCollectorConnectionString
        - name: security-connection-string
          secret:
            secretName: cognigy-service-security
            items:
              - key: connection-string
                path: securityConnectionString
        - name: conversations-connection-string
          secret:
            secretName: cognigy-service-analytics-conversation-collector-provider
            items:
              - key: connection-string
                path: conversationsConnectionString
        - name: redis-password
          secret:
            secretName: cognigy-redis-password
      imagePullSecrets:
        - name: cognigy-registry-token
